import { currency } from "../scripts/utils/money.js";
if(currency(2096.2)=="20.97"){
    console.log("passed");
}
else{
    console.log("failed");
}
if(currency(0)==="0.00"){
    console.log("passed");
}
else{
    console.log("failed");
}
if(currency(2096)=="20.96"){
    console.log("passed");
}
else{
    console.log("failed");
}
if(currency(1000)=="10.00"){
    console.log("passed");
}
else{
    console.log("failed");
}